data:
  parser:
    class_path: MatrixCity
    init_args:
      use_depth: true
model:
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  metric:
    class_path: internal.metrics.inverse_depth_metrics.HasInverseDepthMetrics
  renderer_output_types:
    - rgb
    - inverse_depth
cache_all_images: true