model:
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  density:
    opacity_reset_interval: 999999999  # no reset
  metric:
    class_path: internal.metrics.spotless_metrics.SpotLessMetrics
    init_args:
      max_mlp_mask_size: 400
data:
  parser: internal.dataparsers.spotless_colmap_dataparser.SpotLessColmap
cache_all_images: true