model:
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  density:
    opacity_reset_interval: 999999999  # no reset
  metric:
    class_path: internal.metrics.spotless_metrics.SpotLessMetrics
    init_args:
      lower_bound: 0.3
      upper_bound: 0.8
      lambda_dssim: 0.
data:
  parser: internal.dataparsers.spotless_colmap_dataparser.SpotLessColmap
cache_all_images: true